name: Build and Deploy
on:
  push:
    branches:
      - master
  create:
    tags:
      - 'v*'

jobs:
  build:
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.17.1'
      - run: go version
      - name: Login to GitHub Container Registry
        uses: docker/build-push-action@v1
        if: ${{ matrix.java == '11' }}
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
      - name: Login to Official Container Registry
        uses: docker/build-push-action@v1
        if: ${{ matrix.java == '11' }}
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build
        run: make
      - name: Test
        run: make test
      - name: Deploy Docker Image
        run: make deploy
      - name: Deploy Latest Image
        if: ${{ github.ref_name == 'master' }}
        run: make deploy-latest
      - name: Upload Executable
        uses: actions/upload-artifact@v1
        with:
          name: identicons
          path: target/identicons_*.tar.gz
