name: Build and Deploy
on:
  push:
  create:
    tags:
      - 'v*'

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.17.1'
      - run: go version
      - name: Build
        run: make
      - name: Test
        run: make test
      - uses: actions/upload-artifact@master
        with:
          name: executables
          path: ${{ github.workspace }}/target/**/*
  deploy-versioned:
    name: Deploy Versioned Container
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@master
        with:
          name: executables
          path: ${{ github.workspace }}/target/
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
      - name: Login to Official Container Registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build & Deploy Latest Docker Image
        run: update-binfmts --enable && make docker-multiarch-versioned
  deploy-dev:
    name: Deploy dev Container
    runs-on: ubuntu-latest
    if: ${{ github.ref_name == 'master' }}
    needs: build
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@master
        with:
          name: executables
          path: ${{ github.workspace }}/target/
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
      - name: Login to Official Container Registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build & Deploy Latest Docker Image
        run: update-binfmts --enable && make docker-multiarch-dev
  deploy-latest:
    name: Deploy Container
    runs-on: ubuntu-latest
    if: ${{ github.ref_name == 'master' }}
    needs: build
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@master
        with:
          name: executables
          path: ${{ github.workspace }}/target/
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
      - name: Login to Official Container Registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build & Deploy Latest Docker Image
        run: update-binfmts --enable && make docker-multiarch-latest
