name: Build and Deploy
on:
  push:
    branches:
      - master
  create:
    tags:
      - 'v*'

jobs:
  build:
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.17.1'
      - run: go version
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
      - name: Login to Official Container Registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build
        run: make
      - name: Test
        run: make test
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build & Deploy Latest Docker Image
        if: ${{ github.ref_name == 'master' }}
        run: update-binfmts --enable && make docker-multiarch-master
      - name: Build & Deploy Versioned Docker Image
        if: ${{ github.ref_name != 'master' }}
        run: update-binfmts --enable && make docker-multiarch
