name: Validate
on:
  push:
    branches-ignore:
      - master
      - develop
  pull_request:

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.17.1'
      - run: go version
      - name: Build
        run: make
      - name: Upload Executable
        uses: actions/upload-artifact@v1
        with:
          name: executables
          path: ${{ github.workspace }}/target/**/*
      - name: Test
        run: make test
